
site_name: AespaOS Dev Docs
site_description: Documentation for AespaOS Development
site_author: Solarius Corporation
site_url: https://docs.aespadev.ml/

repo_name: SolariusCorporation/AespaDocs
repo_url: https://github.com/SolariusCorporation/Test
edit_uri: ""

theme:
  logo: https://user-images.githubusercontent.com/51117782/104590568-71724f80-5663-11eb-9bc1-344fc2a4193c.png
  favicon: https://user-images.githubusercontent.com/51117782/104590568-71724f80-5663-11eb-9bc1-344fc2a4193c.png
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  palette:
    primary: blue
    accent: blue
    scheme: preference
  highlightjs: true
  hljs_languages:
    - lua
    - json
    - xml
    - java

extra_javascript:
  - javascripts/tags.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jjjjjj/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jjjjjjjjjjj
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/jjjjj

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences

nav:
  - Home:
    - Introduction: index.md
    - Examples: examples.md
    - Installation: installation.md
    - Method: method.md
    - Third Parties: third_parties.md
    - API:
      - Zone: api/zone.md
      - ZoneController: api/zone_controller.md
    - Resources: resources.md
  - Contributing: contributing.md
  - Changelog: changelog.md